### ISSUE TITLE
Data List for Profile Page

### ISSUE THREAD

**Issue by riazaia** [Fandom-Coders/AO3.js#10]
### Profile Page
(https://archiveofourown.org/users/{username})
- [x] url
- [x] username
- [x] profile picture
- [x] title
- [x] pseuds
- [x] join date
- [x] id
- [x] location
- [x] date of birth
- [x] email adress
- [x] bio
- [x] number of works
- [x] number of series
- [x] number of bookmarks
- [x] number of collections
- [x] number of gifts

**Comment by cyrusae** [comment]
- [x] profile picture
- [x] title

Think I know how to add the others, will do separately building on this one though

**Comment by cyrusae** [comment]
- [x] number of works
- [x] number of series
- [x] number of collections
- [x] number of gifts
- [x] number of bookmarks
also:
- [x] additional test to make sure all of the above works
- [x] note in tests explaining that tests may fail in case of user data change

**Comment by essential-randomness** [comment]
This is now completed
